---
deployment:
  tasks:
    - /bin/cp index.html /home/manycez2q2t3/public_html/
    - /bin/cp contact.php /home/manycez2q2t3/public_html/
    - /bin/cp .htaccess /home/manycez2q2t3/public_html/
    - /bin/cp favicon.png /home/manycez2q2t3/public_html/
    - /bin/cp logo.png /home/manycez2q2t3/public_html/
    - /bin/cp mining-image.png /home/manycez2q2t3/public_html/
    - /bin/cp processing-image.png /home/manycez2q2t3/public_html/
