---
deployment:
  tasks:
    - export DEPLOYPATH=/home/manycez2q2t3/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp favicon.png $DEPLOYPATH
    - /bin/cp logo.png $DEPLOYPATH
    - /bin/cp mining-image.png $DEPLOYPATH
    - /bin/cp processing-image.png $DEPLOYPATH
